name: vk
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  popover: ^0.2.8+2
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf


